# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/protobuf/DataMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/protobuf/DataMessage.proto',
  package='ProtobufDataMessage',
  serialized_pb=_b('\n#protocol/protobuf/DataMessage.proto\x12\x13ProtobufDataMessage\"\x87\x03\n\x0b\x44\x61taMessage\x12\x11\n\tstationId\x18\x01 \x02(\t\x12\x0e\n\x06\x61piKey\x18\x02 \x02(\t\x12\r\n\x05token\x18\x03 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\r\x12<\n\tdataItems\x18\x05 \x03(\x0b\x32).ProtobufDataMessage.DataMessage.DataItem\x1ao\n\x08\x44\x61taItem\x12\x13\n\x0bparameterId\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\x02\x12?\n\x05\x61lert\x18\x03 \x01(\x0e\x32&.ProtobufDataMessage.DataMessage.Alert:\x08NO_ALERT\"\x83\x01\n\x05\x41lert\x12\x11\n\rCRITICAL_HIGH\x10\x03\x12\x0c\n\x08TOO_HIGH\x10\x02\x12\x08\n\x04HIGH\x10\x01\x12\x0c\n\x08NO_ALERT\x10\x00\x12\x10\n\x03LOW\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x14\n\x07TOO_LOW\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n\x0c\x43RITICAL_LOW\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x42:\n3net.bieli.HomeStation.protocol.protobuf.DataMessageH\x01\x90\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DATAMESSAGE_ALERT = _descriptor.EnumDescriptor(
  name='Alert',
  full_name='ProtobufDataMessage.DataMessage.Alert',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CRITICAL_HIGH', index=0, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_HIGH', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH', index=2, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_ALERT', index=3, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=4, number=-1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_LOW', index=5, number=-2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL_LOW', index=6, number=-3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=321,
  serialized_end=452,
)
_sym_db.RegisterEnumDescriptor(_DATAMESSAGE_ALERT)


_DATAMESSAGE_DATAITEM = _descriptor.Descriptor(
  name='DataItem',
  full_name='ProtobufDataMessage.DataMessage.DataItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameterId', full_name='ProtobufDataMessage.DataMessage.DataItem.parameterId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ProtobufDataMessage.DataMessage.DataItem.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alert', full_name='ProtobufDataMessage.DataMessage.DataItem.alert', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=318,
)

_DATAMESSAGE = _descriptor.Descriptor(
  name='DataMessage',
  full_name='ProtobufDataMessage.DataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stationId', full_name='ProtobufDataMessage.DataMessage.stationId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apiKey', full_name='ProtobufDataMessage.DataMessage.apiKey', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='ProtobufDataMessage.DataMessage.token', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ProtobufDataMessage.DataMessage.timestamp', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataItems', full_name='ProtobufDataMessage.DataMessage.dataItems', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAMESSAGE_DATAITEM, ],
  enum_types=[
    _DATAMESSAGE_ALERT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=452,
)

_DATAMESSAGE_DATAITEM.fields_by_name['alert'].enum_type = _DATAMESSAGE_ALERT
_DATAMESSAGE_DATAITEM.containing_type = _DATAMESSAGE
_DATAMESSAGE.fields_by_name['dataItems'].message_type = _DATAMESSAGE_DATAITEM
_DATAMESSAGE_ALERT.containing_type = _DATAMESSAGE
DESCRIPTOR.message_types_by_name['DataMessage'] = _DATAMESSAGE

DataMessage = _reflection.GeneratedProtocolMessageType('DataMessage', (_message.Message,), dict(

  DataItem = _reflection.GeneratedProtocolMessageType('DataItem', (_message.Message,), dict(
    DESCRIPTOR = _DATAMESSAGE_DATAITEM,
    __module__ = 'protocol.protobuf.DataMessage_pb2'
    # @@protoc_insertion_point(class_scope:ProtobufDataMessage.DataMessage.DataItem)
    ))
  ,
  DESCRIPTOR = _DATAMESSAGE,
  __module__ = 'protocol.protobuf.DataMessage_pb2'
  # @@protoc_insertion_point(class_scope:ProtobufDataMessage.DataMessage)
  ))
_sym_db.RegisterMessage(DataMessage)
_sym_db.RegisterMessage(DataMessage.DataItem)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3net.bieli.HomeStation.protocol.protobuf.DataMessageH\001\220\001\001'))
# @@protoc_insertion_point(module_scope)
