sudo: false
language: python

python:
 - "3.4"
 - "3.5"

install:
 - pip install -r requirements.txt

script:
 - coverage run HomeStation/*/*.py
 # - nosetests  --with-coverage --cover-package=./HomeStation/
 - coverage run --source=HomeStation HomeStation/tests/
 - python -m unittest discover ./HomeStation/tests/ "*Test.py"

after_success:
 - COVERALLS_REPO_TOKEN=On1CE31FvjHFmi3Vg13tPbORVonaxr0aZ coveralls debug

notifications:
 - email: false
 
