sudo: false

language: python

python:
 - "2.6"
 - "2.7"
 - "pypy"

#install: pip install .

#before_script:
#  - pip install .

script: python -m unittest discover ./HomeStation/tests/ "*Test.py"

notifications:
  email: false